[project]
name = "kmong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.3.0",
    "pygetwindow>=0.0.9",
    "ultralytics>=8.3.176",
]
